version: '3'
services:
  db-dev:
    image: postgres:16.2-alpine
    container_name: pt_dev_db
    environment:
      POSTGRES_DB: pt_dev_db
      POSTGRES_USER: pt_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
  db-test:
    image: postgres:16.2-alpine
    container_name: pt_test_db
    environment:
      POSTGRES_DB: pt_test_db
      POSTGRES_USER: pt_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
